/*
 * Click nfs://netbeans/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nfs://netbeans/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.adso.el_taller_de_adso.servicios;
import com.adso.el_taller_de_adso.servicios.ServicioDAO;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.sql.Date;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author USUARIO
 */
public class MarcoServicios extends javax.swing.JInternalFrame {

    private ServicioDAO servicioDAO = new ServicioDAO();
    private DefaultTableModel tableModel;

    /**
     * Creates new form MarcoServicios
     */
    public MarcoServicios() {
        initComponents();
        initializeComponents();
    }

    private void initializeComponents() {
    // Populate combo boxes with data from the database
    jComboBoxseleccioncliente.setModel(new DefaultComboBoxModel<>(servicioDAO.getAllClientes().toArray(new String[0])));
    jComboBoxseleccionvehiculo.setModel(new DefaultComboBoxModel<>(servicioDAO.getAllVehiculos().toArray(new String[0])));
    jComboBoxtipodeservicio.setModel(new DefaultComboBoxModel<>(new String[]{"cambio de aceite", "lavado", "mantenimiento general"}));

    // Initialize table model
    tableModel = (DefaultTableModel) jTableproductosseleccionados.getModel();
    jTextFieldtotalservicio.setEditable(false); // Make total read-only
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxtipodeservicio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxseleccionvehiculo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxseleccioncliente = new javax.swing.JComboBox<>();
        jButtonagregarrepuestos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproductosseleccionados = new javax.swing.JTable();
        jButtonguardarservicio = new javax.swing.JButton();
        jTextFieldtotalservicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooserfechadelservicio = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agregar Servicio");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha del servicio:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Selecciona el cliente:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de servicio:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Selecciona el vehiculo:");

        jButtonagregarrepuestos.setText("Agregar repuestos");
        jButtonagregarrepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonagregarrepuestosActionPerformed(evt);
            }
        });

        jTableproductosseleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Precio unitario", "Cantidad disponible"
            }
        ));
        jScrollPane1.setViewportView(jTableproductosseleccionados);

        jButtonguardarservicio.setText("Guardar Servicio");
        jButtonguardarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguardarservicioActionPerformed(evt);
            }
        });

        jTextFieldtotalservicio.setText("0");
        jTextFieldtotalservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtotalservicioActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Productos seleccionados:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("total del servicio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jComboBoxseleccionvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxtipodeservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jComboBoxseleccioncliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3)))
                                    .addComponent(jLabel4)
                                    .addComponent(jDateChooserfechadelservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jButtonguardarservicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonagregarrepuestos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtotalservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(183, 183, 183))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooserfechadelservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxtipodeservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxseleccioncliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBoxseleccionvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                .addComponent(jButtonagregarrepuestos)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonguardarservicio))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldtotalservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonguardarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguardarservicioActionPerformed
        // TODO add your handling code here:
        if (jDateChooserfechadelservicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, agrega al menos un repuesto antes de guardar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Servicio servicio = new Servicio();
        servicio.setFecha(new Date(jDateChooserfechadelservicio.getDate().getTime()));
        servicio.setTipo((String) jComboBoxtipodeservicio.getSelectedItem());
        // Replace comma with dot for proper parsing
        String costText = jTextFieldtotalservicio.getText().replace(",", ".");
        servicio.setCosto(Double.parseDouble(costText));
        servicio.setPagado(false); // Default to false, can be updated later
        servicio.setVehiculoId(servicioDAO.getVehiculoId((String) jComboBoxseleccionvehiculo.getSelectedItem()));
        servicio.setClienteId(servicioDAO.getClienteId((String) jComboBoxseleccioncliente.getSelectedItem()));

        try {
            servicioDAO.addServicio(servicio, tableModel);
            JOptionPane.showMessageDialog(this, "Servicio guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el servicio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonguardarservicioActionPerformed

private void jButtonagregarrepuestosActionPerformed(java.awt.event.ActionEvent evt) {
    String[] products = servicioDAO.getAllProductos().toArray(new String[0]);
    String selectedProduct = (String) JOptionPane.showInputDialog(
        this, "Selecciona un repuesto:", "Agregar Repuestos",
        JOptionPane.PLAIN_MESSAGE, null, products, products[0]);
    
    if (selectedProduct != null) {
        String quantityStr = JOptionPane.showInputDialog(this, "Ingresa la cantidad:", "1");
        try {
            int quantity = Integer.parseInt(quantityStr != null ? quantityStr.trim() : "0");
            if (quantity > 0) {
                int availableStock = servicioDAO.getProductoStock(selectedProduct);
                if (quantity <= availableStock) {
                    double price = servicioDAO.getPrecioProducto(selectedProduct);
                    String description = servicioDAO.getProductoDescription(selectedProduct) != null ? 
                                        servicioDAO.getProductoDescription(selectedProduct) : "Sin descripción";
                    tableModel.addRow(new Object[]{selectedProduct, description, price, quantity});
                    updateTotalCost();
                } else {
                    JOptionPane.showMessageDialog(this, "Stock insuficiente. Disponible: " + availableStock, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

    

    private void jTextFieldtotalservicioActionPerformed(java.awt.event.ActionEvent evt) {
        // No action needed here unless you want to trigger something specific
    }

    private void updateTotalCost() {
        double total = 0;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Object priceObj = tableModel.getValueAt(i, 2);
            Object quantityObj = tableModel.getValueAt(i, 3);
            if (priceObj != null && quantityObj != null) {
                double price = (priceObj instanceof Number) ? ((Number) priceObj).doubleValue() : 0.0;
                int quantity = (quantityObj instanceof Number) ? ((Number) quantityObj).intValue() : 0;
                total += price * quantity;
            }
        }
        // Use NumberFormat to ensure consistent decimal formatting
        NumberFormat nf = NumberFormat.getNumberInstance(Locale.US);
        if (nf instanceof java.text.DecimalFormat) {
            ((java.text.DecimalFormat) nf).setGroupingUsed(false); // Disable grouping (e.g., no commas as thousand separators)
        }
        jTextFieldtotalservicio.setText(nf.format(total));
    }

    private void clearForm() {
        jDateChooserfechadelservicio.setDate(null);
        jComboBoxtipodeservicio.setSelectedIndex(0);
        jComboBoxseleccioncliente.setSelectedIndex(0);
        jComboBoxseleccionvehiculo.setSelectedIndex(0);
        tableModel.setRowCount(0);
        jTextFieldtotalservicio.setText("0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonagregarrepuestos;
    private javax.swing.JButton jButtonguardarservicio;
    private javax.swing.JComboBox<String> jComboBoxseleccioncliente;
    private javax.swing.JComboBox<String> jComboBoxseleccionvehiculo;
    private javax.swing.JComboBox<String> jComboBoxtipodeservicio;
    private com.toedter.calendar.JDateChooser jDateChooserfechadelservicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableproductosseleccionados;
    private javax.swing.JTextField jTextFieldtotalservicio;
    // End of variables declaration//GEN-END:variables
}