/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.adso.el_taller_de_adso.clientes;

import javax.swing.table.DefaultTableModel;
import com.adso.el_taller_de_adso.clientes.ClienteDAO;
import com.adso.el_taller_de_adso.clientes.Cliente;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author axchisan
 */
public class MarcoGestionClientes extends javax.swing.JInternalFrame {
public ClienteDAO clienteDAO;
public DefaultTableModel modeloTabla;

    /**
     * Creates new form MarcoGestionClientes
     */
    public MarcoGestionClientes() {
        clienteDAO = new ClienteDAO();
        initComponents();
        configurartabla();
        cargarClientes();
        tablaClientes.getSelectionModel().addListSelectionListener(e -> seleccionarCliente());
        setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCriterioBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelEdicion = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblVacio1 = new javax.swing.JLabel();
        lblVacio2 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelClientes = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GestionClientes");
        setPreferredSize(new java.awt.Dimension(800, 600));

        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));

        jLabel1.setText("Criterio");
        panelBusqueda.add(jLabel1);

        cbCriterioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "documento", "nombre" }));
        panelBusqueda.add(cbCriterioBusqueda);

        txtBuscar.setMinimumSize(new java.awt.Dimension(200, 25));
        panelBusqueda.add(txtBuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar);

        getContentPane().add(panelBusqueda, java.awt.BorderLayout.PAGE_START);

        panelEdicion.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Cliente"));
        panelEdicion.setPreferredSize(new java.awt.Dimension(0, 200));
        panelEdicion.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        lblNombre.setText("Nombre");
        panelEdicion.add(lblNombre);
        panelEdicion.add(txtNombre);

        lblDocumento.setText("Documento");
        panelEdicion.add(lblDocumento);
        panelEdicion.add(txtDocumento);

        lblTelefono.setText("Teléfono");
        panelEdicion.add(lblTelefono);
        panelEdicion.add(txtTelefono);

        lblCorreo.setText("Correo");
        panelEdicion.add(lblCorreo);
        panelEdicion.add(txtCorreo);
        panelEdicion.add(lblVacio1);
        panelEdicion.add(lblVacio2);

        panelBotones.setAlignmentY(5.0F);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelBotones.add(btnActualizar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEliminar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelBotones.add(btnLimpiar);

        panelEdicion.add(panelBotones);

        getContentPane().add(panelEdicion, java.awt.BorderLayout.PAGE_END);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Documento", "Teléfono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelClientes.setViewportView(tablaClientes);

        getContentPane().add(panelClientes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarclientes();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarCliente();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarCliente();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbCriterioBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblVacio1;
    private javax.swing.JLabel lblVacio2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane panelClientes;
    private javax.swing.JPanel panelEdicion;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
private void configurartabla(){
    modeloTabla = (DefaultTableModel) tablaClientes.getModel();
    modeloTabla.setRowCount(0);
}
private void cargarClientes(){
    modeloTabla.setRowCount(0);
    List<Cliente> clientes = clienteDAO.listarClientes();
    for (Cliente cliente : clientes){
        modeloTabla.addRow(new Object[]{
            cliente.getId(),
            cliente.getNombre(),
            cliente.getDocumento(),
            cliente.getTelefono(),
            cliente.getCorreo(),
            cliente.getRol()
        });
    }
}

private void buscarclientes(){
    String criterio = cbCriterioBusqueda.getSelectedItem().toString().toLowerCase();
    String valor = txtBuscar.getText().trim();
    modeloTabla.setRowCount(0);
    List<Cliente> clientes = clienteDAO.buscarCliente(criterio, valor);
    for (Cliente cliente : clientes){
        modeloTabla.addRow(new Object[]{
            cliente.getId(),
            cliente.getNombre(),
            cliente.getDocumento(),
            cliente.getTelefono(),
            cliente.getCorreo(),
            cliente.getRol()
        });        
    }
    if (clientes.isEmpty()){
        JOptionPane.showMessageDialog(this, "no se encontraron clientes", "Información", JOptionPane.INFORMATION_MESSAGE);
    }
}

private void seleccionarCliente() {
        int fila = tablaClientes.getSelectedRow();
        if (fila >= 0) {
            txtNombre.setText(modeloTabla.getValueAt(fila, 1).toString());
            txtDocumento.setText(modeloTabla.getValueAt(fila, 2).toString());
            txtTelefono.setText(modeloTabla.getValueAt(fila, 3).toString());
            txtCorreo.setText(modeloTabla.getValueAt(fila, 4).toString());
        }
    }

    private void actualizarCliente() {
        String documento = txtDocumento.getText().trim();
        if (documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para actualizar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombre = txtNombre.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cliente cliente = new Cliente(0, nombre, documento, telefono, correo, 1); // Rol fijo, ajustar si es dinámico
        clienteDAO.actualizarCliente(cliente);
        limpiarFormulario();
        cargarClientes();
    }

    private void eliminarCliente() {
        String documento = txtDocumento.getText().trim();
        if (documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este cliente?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                clienteDAO.eliminarCliente(documento);
                limpiarFormulario();
                cargarClientes();
            } catch (Exception e) {
                if (e.getMessage().contains("23503")) { // Violación de clave foránea
                    JOptionPane.showMessageDialog(this, "No se puede eliminar el cliente porque tiene vehículos o servicios asociados", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtDocumento.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtBuscar.setText("");
        cargarClientes();
    }
}
